version: '3.7'

services:
  fastapi-app:
    image: lipstick-db-fastapi:latest
    restart: always
    ports:
      - 8000:9000
    depends_on:
      - flow-service
      - minio-service
    environment:
      - JINA_HOST=grpc://flow-service:8888
      - S3_ENDPOINT_URL=http://minio-service:9000
      - S3_ACCESS_KEY_ID=minio
      - S3_SECRET_ACCESS_KEY=minio123
      - S3_REGION=local
      - S3_BUCKET_NAME=lipstick-db
  flow-service:
    image: lipstick-db-jina:latest
    restart: always
    ports:
      - 8888:8888
    command: make jina-app
    environment:
      - JINA_LOG_LEVEL=DEBUG
    depends_on:
      - face-mesher
      - s3-downloader
      - lip-skin-color-embedder
      - matcher
  s3-downloader:
    image: lipstick-db-jina:latest
    restart: always
    ports:
      - 8887:8887
    command: jina executor --uses s3_downloader.yml --port 8887
    environment:
      - JINA_LOG_LEVEL=DEBUG
      - S3_ENDPOINT_URL=http://minio-service:9000
      - S3_ACCESS_KEY_ID=minio
      - S3_SECRET_ACCESS_KEY=minio123
      - S3_REGION=local
      - S3_BUCKET_NAME=lipstick-db
    depends_on:
      - minio-service
  face-mesher:
    image: lipstick-db-jina:latest
    restart: always
    ports:
      - 8886:8886
    command: jina executor --uses face_mesher.yml --port 8886
    environment:
      - JINA_LOG_LEVEL=DEBUG
  lip-skin-color-embedder:
    image: lipstick-db-jina:latest
    restart: always
    ports:
      - 8885:8885
    command: jina executor --uses lip_skin_color_embedder.yml --port 8885
    environment:
      - JINA_LOG_LEVEL=DEBUG
  matcher:
    image: lipstick-db-jina:latest
    restart: always
    ports:
      - 8884:8884
    command: jina executor --uses matcher.yml --port 8884
    environment:
      - JINA_LOG_LEVEL=DEBUG
  minio-service:
    restart: unless-stopped
    image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    ports:
      - '9000:9000'
      - '9001:9001'
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio-data:/data

volumes:
  minio-data:
    driver: local
